language: ruby

script: bundle exec rake $TASK

sudo: false

rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - jruby-head
  - ruby-head

env:
  - TASK=rspec
  - TASK=mutant

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
    - env: TASK=mutant

  # Only run mutant on 2.2
  exclude:
    - rvm: 2.0
      env: TASK=mutant
    - rvm: 2.1
      env: TASK=mutant
    - rvm: jruby
      env: TASK=mutant
    - rvm: jruby-head
      env: TASK=mutant
    - rvm: rbx
      env: TASK=mutant
    - rvm: ruby-head
      env: TASK=mutant
